name: ghc-lexer-example
version: '0.0.1-SNAPSHOT'
category: Language
author: Cary Robbins
maintainer: Cary Robbins
license: AllRightsReserved
github: githubuser/ghc-lexer-example
extra-source-files:
- README.md
executables:
  ghc-lexer-example:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - ghc
    - ghc-paths
