name: ghc-lexer-example
version: '0.0.1-SNAPSHOT'
category: Language
author: Cary Robbins
maintainer: Cary Robbins
license: AllRightsReserved
github: githubuser/ghc-lexer-example
extra-source-files:
- README.md
source-dirs: src
ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
dependencies:
- base
- ghc
- ghc-paths

executables:
  ghc-lexer-example:
    main: Main.hs
  ghc-lexer-io:
    main: LexerIO.hs
